// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgBTtEVCIroMkdihpsAuCQIWr1hjI6sQo',
    appId: '1:280025843834:web:e7b634312a993d1af793c3',
    messagingSenderId: '280025843834',
    projectId: 'authentecation-b2c42',
    authDomain: 'authentecation-b2c42.firebaseapp.com',
    storageBucket: 'authentecation-b2c42.appspot.com',
    measurementId: 'G-VPMQSEET7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf0bsrELxaMIvRzD69PS6CJGbiBUquR7o',
    appId: '1:280025843834:android:69f18913c77e0361f793c3',
    messagingSenderId: '280025843834',
    projectId: 'authentecation-b2c42',
    storageBucket: 'authentecation-b2c42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-lu-RboUjQYcx8C-QZroGZHrwwmKFbeU',
    appId: '1:280025843834:ios:6e9070e2ee82518df793c3',
    messagingSenderId: '280025843834',
    projectId: 'authentecation-b2c42',
    storageBucket: 'authentecation-b2c42.appspot.com',
    iosClientId: '280025843834-2uckb9mcati56dl7q0jrapqcjq3hr1df.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-lu-RboUjQYcx8C-QZroGZHrwwmKFbeU',
    appId: '1:280025843834:ios:409f7beb75f3eda1f793c3',
    messagingSenderId: '280025843834',
    projectId: 'authentecation-b2c42',
    storageBucket: 'authentecation-b2c42.appspot.com',
    iosClientId: '280025843834-5g9q0evme65hr6scn5eqcajp7v63r3r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
